kind: pipeline
type: kubernetes
name: default

steps:
- name: Deploy
  image: vallard/drone-kube
  settings:
    template: kube.yml
    ca:
      from_secret: cert
    server: https://B235FE188E9A46B15766BE898067F3FB.gr7.eu-central-1.eks.amazonaws.com
    token:
      from_secret: token
