kind: pipeline
name: default
type: kubernetes

steps:
- name: deploy
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_server:
      from_secret:  url
    kubernetes_token:
      from_secret: token
    namespace: app
    deployment: my-deployment
    # repo: myorg/myrepo
    container: dockersamples/k8s-wordsmith-web
    tag: mytag