kind: pipeline
name: default
steps:
- name: helm_deploy
  image: fpedrazas/drone-helm
  settings:
    skip_tls_verify: true
    chart: ./
    release: ${DRONE_BRANCH}
    #values: secret.password=${SECRET_PASSWORD},image.tag=${TAG}
    prefix: STAGING
    namespace: starting
