kind: pipeline
name: default

steps:
- name: deploy_production
  image: pelotech/drone-helm3
  settings:
    helm_command: upgrade
    chart: ./
    release: my-project
 #   api_server:
 #     from_secret: prod_api_server
 #   kubernetes_token:
 #     from_secret: prod_kubernetes_token
