kind: pipeline
name: default

steps:
- name: deploy
  image: pelotech/drone-helm3
  settings:
    helm_command: upgrade
    chart: template/
    release: my-project
    api_server:
      from_secret: url
    kubernetes_token:
      from_secret: token