kind: pipeline
name: default

steps:
- name: deploy_production
  image: pelotech/drone-helm3
  settings:
    helm_command: upgrade
    chart: ./
    release: my-project
    kube_api_server: https://192.168.59.103:8443
#    api_server: 
#      from_secret:
    kubernetes_token:
      from_secret: default-token-rfnqw
