kind: pipeline
name: default

steps:
- name: deploy
  image: pelotech/drone-helm3
  settings:
    helm_command: upgrade
    chart: template/
    release: my-project
    api_server: https://api.cluster.turali7v.click
    kubernetes_token:
      from_secret: k8s_token
    kube_certificate:
      from_secret: k8s_cert
  debug: true